import copy
import pytest

from manubot.cite.csl_item import (
    csl_item_set_standard_id,
    CSL_Item)


class Test_CSL_Item:

    def test_constuctor_empty(self):
        assert CSL_Item() == {}

    def test_constuctor_non_empty(self):
        d = {'k1': 1}
        assert CSL_Item(d) == d

    def test_add_note_manubot_version_on_fixed_version(self):
        assert CSL_Item().add_note_manubot_version('1.1.1')['note'] == \
             'This CSL JSON Item was automatically generated by Manubot v1.1.1 using citation-by-identifier.'

    def test_add_note_manubot_version(self):
        string = CSL_Item().add_note_manubot_version()['note']
        assert string.startswith('This CSL JSON Item')

    def test_add_note_standard_id_and_note_dict(self):
         assert CSL_Item().add_note_standard_id('abc').note_dict() == \
            {'standard_id': 'abc'}

    def test_fixtype(self):
        assert CSL_Item(dict(type='journal-article')).fix_type() == \
            {'type': 'article-journal'}         



@pytest.mark.parametrize(
    ['csl_item', 'standard_citation'],
    [
        (
            {'id': 'my-id', 'standard_citation': 'doi:10.7554/elife.32822'},
            'doi:10.7554/elife.32822',
        ),
        (
            {'id': 'doi:10.7554/elife.32822'},
            'doi:10.7554/elife.32822',
        ),
        (
            {'id': 'doi:10.7554/ELIFE.32822'},
            'doi:10.7554/elife.32822',
        ),
        (
            {'id': 'my-id'},
            'raw:my-id',
        ),
    ],
    ids=[
        'from_standard_citation',
        'from_doi_id',
        'from_doi_id_standardize',
        'from_raw_id',
    ]
)
def test_csl_item_set_standard_id(csl_item, standard_citation):
    output = csl_item_set_standard_id(csl_item)
    assert output is csl_item
    assert output['id'] == standard_citation


def test_csl_item_set_standard_id_repeated():
    csl_item = {
        'id': 'pmid:1',
        'type': 'article-journal',
    }
    # csl_item_0 = copy.deepcopy(csl_item)
    csl_item_1 = copy.deepcopy(csl_item_set_standard_id(csl_item))
    assert 'standard_citation' not in 'csl_item'
    csl_item_2 = copy.deepcopy(csl_item_set_standard_id(csl_item))
    assert csl_item_1 == csl_item_2


def test_csl_item_set_standard_id_note():
    """
    Test extracting standard_id from a note and setting additional
    note fields.
    """
    csl_item = {
        'id': 'original-id',
        'type': 'article-journal',
        'note': 'standard_id: doi:10.1371/journal.PPAT.1006256',
    }
    csl_item_set_standard_id(csl_item)
    assert csl_item['id'] == 'doi:10.1371/journal.ppat.1006256'
    from manubot.cite.citeproc import parse_csl_item_note
    note_dict = parse_csl_item_note(csl_item['note'])
    assert note_dict['original_id'] == 'original-id'
    assert note_dict['original_standard_id'] == 'doi:10.1371/journal.PPAT.1006256'

